create table MATCH_LOCATION
(
   LOCATION_ID          int(8) not null auto_increment  comment '',
   CODE                 varchar(3) not null  comment '',
   MATCH_ID             int not null  comment '',
   AVAILABILITY         decimal(3,0) not null  comment '',
   PRICE                decimal(5,2) not null  comment '',
   primary key (LOCATION_ID)
);

/*==============================================================*/
/* Table: SOCCER_MATCH                                          */
/*==============================================================*/
create table SOCCER_MATCH
(
   MATCH_ID             int(8) not null auto_increment  comment '',
   LOCAL_TEAM           varchar(64) not null  comment '',
   VISITING_TEAM        varchar(64) not null  comment '',
   DATE                 date not null  comment '',
   SITE                 varchar(128) not null  comment '',
   primary key (MATCH_ID)
);

alter table MATCH_LOCATION add constraint FK_MATCH_LO_REFERENCE_SOCCER_M foreign key (MATCH_ID)
      references SOCCER_MATCH (MATCH_ID) on delete restrict on update restrict;


INSERT INTO SOCCER_MATCH(LOCAL_TEAM, VISITING_TEAM, DATE, SITE) VALUES("Team 1", "Team 2", "2022-01-01", "Stadium 1");
INSERT INTO SOCCER_MATCH(LOCAL_TEAM, VISITING_TEAM, DATE, SITE) VALUES("Team 2", "Team 3", "2022-01-02", "Stadium 2");
INSERT INTO SOCCER_MATCH(LOCAL_TEAM, VISITING_TEAM, DATE, SITE) VALUES("Team 3", "Team 4", "2022-01-03", "Stadium 3");
INSERT INTO SOCCER_MATCH(LOCAL_TEAM, VISITING_TEAM, DATE, SITE) VALUES("Team 4", "Team 5", "2022-01-04", "Stadium 4");
INSERT INTO SOCCER_MATCH(LOCAL_TEAM, VISITING_TEAM, DATE, SITE) VALUES("Team 5", "Team 1", "2022-01-05", "Stadium 5");

INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("BOX", 11, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("VGE", 11, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("LGE", 11, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("STN", 11, 300, 10.0);

INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("BOX", 12, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("VGE", 12, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("LGE", 12, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("STN", 12, 300, 10.0);

INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("BOX", 13, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("VGE", 13, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("LGE", 13, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("STN", 13, 300, 10.0);


INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("BOX", 14, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("VGE", 14, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("LGE", 14, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("STN", 14, 300, 10.0);

INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("BOX", 15, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("VGE", 15, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("LGE", 15, 300, 10.0);
INSERT INTO MATCH_LOCATION(CODE, MATCH_ID, AVAILABILITY, PRICE) VALUES("STN", 15, 300, 10.0);